### GET /
GET http://localhost:5003

###
POST localhost:5003/auth/register
Content-Type: application/json

{
  "username": "jomo123",
  "password": "123123"
}

###
POST localhost:5003/auth/login
Content-Type: application/json

{
  "username": "jomo123",
  "password": "123123"
}