### GET /
GET http://localhost:5003

###### Auth Routes

###
POST localhost:5003/auth/register
Content-Type: application/json

{
  "username": "jomo123",
  "password": "123123"
}

###
POST localhost:5003/auth/login
Content-Type: application/json

{
  "username": "jomo123",
  "password": "123123"
}

###

POST localhost:5003/auth/register
Content-Type: application/json

{
  "username": "dovo123",
  "password": "123123"
}

### Invalid Password
POST localhost:5003/auth/login
Content-Type: application/json

{
  "username": "dovo123",
  "password": "123123333"
}

###### User Routes

###
GET localhost:5003/jomo123

###
GET localhost:5003/dovo123

###
PUT localhost:5003/jomo123/links
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJqb21vMTIzIiwiaWF0IjoxNzUwMTA4MDIwLCJleHAiOjE3NTAxOTQ0MjB9.8CLBkjujHzYerZunNnvfjMqbe9akwNdUqIzV2m6gx0o
Content-Type: application/json

[
  {"title": "GitHub", "url": "https://github.com/milljo3"},
  {"title": "Youtube", "url": "https://github.com/milljo3"},
  {"title": "Instagram", "url": "https://github.com/milljo3"},
  {"title": "Portfolio", "url": "https://github.com/milljo3"}
]

### Invalid Jwt
PUT localhost:5003/jomo123/links
Authorization: invalid
Content-Type: application/json

[
  {"title": "GitHub", "url": "https://github.com/milljo3"},
  {"title": "Youtube", "url": "https://github.com/milljo3"},
  {"title": "Instagram", "url": "https://github.com/milljo3"},
  {"title": "Portfolio", "url": "https://github.com/milljo3"}
]