version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: devlink-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRESS_USER}
      POSTGRES_PASSWORD: ${POSTGRESS_PASSWORD}
      POSTGRES_DB: devlink
    ports:
      - "5432:5432"
    volumes:
      - devlink-postgres-data:/var/lib/postgresql/data

volumes:
  devlink-postgres-data:
